# Generated by Django 3.0.6 on 2020-05-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_picture',
        ),
    ]
