# Generated by Django 3.0.6 on 2020-05-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20200515_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
