# Generated by Django 3.0.6 on 2020-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_remove_choice_choice_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
