# Generated by Django 3.0.6 on 2020-05-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
